version: '{build}'
skip_tags: true
clone_depth: 10
environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
branches:
  only:
    - master
  except:
    - gh-pages
os: Windows Server 2012
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile('http://apache.mirrors.tds.net/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip', 'C:\maven-bin.zip')
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET PATH=C:\maven\apache-maven-3.3.9\bin;%JAVA_HOME%\bin;%PATH:C:\Ruby193\bin;=%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
  - cmd: SET org.ojalgo.OjAlgoUtils.ENVIRONMENT=x86_64
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn clean
test_script:
  - mvn test
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
