/**
 * This software is released under the University of Illinois/Research and Academic Use License. See
 * the LICENSE file in the root folder for details. Copyright (c) 2016
 *
 * Developed by: The Cognitive Computation Group University of Illinois at Urbana-Champaign
 * http://cogcomp.org/
 */
package edu.illinois.cs.cogcomp.core.constants;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * List of languages used in the packages.
 * The code names follow the ISO 639-3 standard.
 * @author Chen-Tse
 * @author Daniel
 */
public enum Language {
    Abkhazian("abk"),
    Afar("aar"),
    Afrikaans("afr"),
    Akan("aka"),
    Albanian("sqi"),
    Amharic("amh"),
    Arabic("ara"),
    Aragonese("arg"),
    Armenian("hye"),
    Assamese("asm"),
    Avaric("ava"),
    Avestan("ave"),
    Aymara("aym"),
    Azerbaijani("aze"),
    Bambara("bam"),
    Bashkir("bak"),
    Basque("eus"),
    Belarusian("bel"),
    Bengali("ben"),
    Bislama("bis"),
    Bosnian("bos"),
    Breton("bre"),
    Bulgarian("bul"),
    Burmese("mya"),
    Valencian("cat"),
    Catalan("cat"),
    Chamorro("cha"),
    Chechen("che"),
    Nyanja("nya"),
    Chichewa("nya"),
    Chewa("nya"),
    Chinese("zho"),
    Chuvash("chv"),
    Cornish("cor"),
    Corsican("cos"),
    Cree("cre"),
    Croatian("hrv"),
    Czech("ces"),
    Danish("dan"),
    Divehi("div"),
    Dutch("nld"),
    Dzongkha("dzo"),
    English("eng"),
    Esperanto("epo"),
    Estonian("est"),
    Ewe("ewe"),
    Faroese("fao"),
    Fijian("fij"),
    Finnish("fin"),
    French("fra"),
    Fulah("ful"),
    Galician("glg"),
    Georgian("kat"),
    German("deu"),
    Greek("ell"),
    Guaraní("grn"),
    Gujarati("guj"),
    Haitian("hat"),
    Hausa("hau"),
    Hebrew("heb"),
    Herero("her"),
    Hindi("hin"),
    Hiri_Motu("hmo"),
    Hungarian("hun"),
    Interlingua("ina"),
    Indonesian("ind"),
    Interlingue("ile"),
    Irish("gle"),
    Igbo("ibo"),
    Inupiaq("ipk"),
    Ido("ido"),
    Icelandic("isl"),
    Italian("ita"),
    Inuktitut("iku"),
    Japanese("jpn"),
    Javanese("jav"),
    Kalaallisut("kal"),
    Kannada("kan"),
    Kanuri("kau"),
    Kashmiri("kas"),
    Kazakh("kaz"),
    Central_Khmer("khm"),
    Kikuyu("kik"),
    Kinyarwanda("kin"),
    Kirghiz("kir"),
    Komi("kom"),
    Kongo("kon"),
    Korean("kor"),
    Kurdish("kur"),
    Kuanyama("kua"),
    Latin("lat"),
    Luxembourgish("ltz"),
    Ganda("lug"),
    Limburgan("lim"),
    Lingala("lin"),
    Lao("lao"),
    Lithuanian("lit"),
    Luba_Katanga("lub"),
    Latvian("lav"),
    Manx("glv"),
    Macedonian("mkd"),
    Malagasy("mlg"),
    Malay("msa"),
    Malayalam("mal"),
    Maltese("mlt"),
    Maori("mri"),
    Marathi("mar"),
    Marshallese("mah"),
    Mongolian("mon"),
    Nauru("nau"),
    Navajo("nav"),
    North_Ndebele("nde"),
    Nepali("nep"),
    Ndonga("ndo"),
    Norwegian_Bokmål("nob"),
    Norwegian_Nynorsk("nno"),
    Norwegian("nor"),
    Sichuan_Yi("iii"),
    South_Ndebele("nbl"),
    Occitan("oci"),
    Ojibwa("oji"),
    Church_Slavic("chu"),
    Oromo("orm"),
    Oriya("ori"),
    Ossetian("oss"),
    Panjabi("pan"),
    Punjabi("pan"),
    Pali("pli"),
    Persian("fas"),
    Polish("pol"),
    Pashto("pus"),
    Portuguese("por"),
    Quechua("que"),
    Romansh("roh"),
    Rundi("run"),
    Romanian("ron"),
    Russian("rus"),
    Sanskrit("san"),
    Sardinian("srd"),
    Sindhi("snd"),
    Northern("Sami	sme"),
    Samoan("smo"),
    Sango("sag"),
    Serbian("srp"),
    Gaelic("gla"),
    Shona("sna"),
    Sinhala("sin"),
    Slovak("slk"),
    Slovenian("slv"),
    Somali("som"),
    Southern_Sotho("sot"),
    Spanish("spa"),
    Castilian("spa"),
    Sundanese("sun"),
    Swahili("swa"),
    Swati("ssw"),
    Swedish("swe"),
    Tamil("tam"),
    Telugu("tel"),
    Tajik("tgk"),
    Thai("tha"),
    Tigrinya("tir"),
    Tibetan("bod"),
    Turkmen("tuk"),
    Tagalog("tgl"),
    Tswana("tsn"),
    Tonga("ton"),
    Turkish("tur"),
    Tsonga("tso"),
    Tatar("tat"),
    Twi("twi"),
    Tahitian("tah"),
    Uyghur("uig"),
    Uighur("uig"),
    Ukrainian("ukr"),
    Urdu("urd"),
    Uzbek("uzb"),
    Venda("ven"),
    Vietnamese("vie"),
    Volapük("vol"),
    Walloon("wln"),
    Welsh("cym"),
    Wolof("wol"),
    Xhosa("xho"),
    Yiddish("yid"),
    Yoruba("yor"),
    Zhuang("zha"),
    Chuang("zha"),
    Zulu("zul"),
    Zazaki("zza"),
    Zeelandic("zea"),
    Sorani("ckb"),
    Egyptian_Arabic("arz"),
    Asturian("ast"),
    Sicilian("scn"),
    Mazandarani("mzn"),
    Waray("war"),
    Upper_Sorbian("hsb"),
    Kabardian("kbd"),
    Nahuatl("nah"),
    Maithili("mai"),
    Limburgish("lim"),
    Scots("sco"),
    Cebuano("ceb"),
    SerboCroatian("sh"),
    Minangkabau("min"),
    Volapuk("vol"),
    Newar("new"),
    Venetian("ven"),
    Vepsian("vep"),
    West_Frisian("fry"),
    Western_Frisian("fry"),
    Western_Punjabi("Western_Punjabi"),
    ;


    private static Logger logger = LoggerFactory.getLogger(Language.class);

    private String code;

    Language(String code) {
        this.code = code;
    }

    public String getCode(){
        return code;
    }

    public static Language getLanguageByCode(String code){

        for(Language lang: Language.values()){
            if(lang.getCode().equals(code))
                return lang;
        }

        logger.error("Unknown language code: "+code);
        return null;
    }
}
